spring.application.name=crud


# ===============================
# DATABASE CONFIG (MySQL)
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/parking?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# CONNECTION POOL (Hikari - default)
# ===============================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

# ===============================
# LOGGING (optional)
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# JWt 
# ===============================
secret_key =Z3VhcmFudGVlZF9zZWN1cmVfMjU2X2JpdHNfanV3dF9rZXlfMTIzNDU2Nzg5MA==


# ===============================
# Hashing pass 
# ===============================
saltKey = "ui43efwmefiwibut4bvhutv4yu"